driver:
  name: vagrant
  chef_version: 12.5.1

provisioner:
  name: chef_zero

platforms:
  - name: centos-5.11
  - name: centos-6.7
  - name: centos-7.2
  - name: debian-7.10
    run_list: apt::default
  - name: debian-8.4
    run_list: apt::default
  - name: fedora-21
  - name: fedora-22
  - name: ubuntu-12.04
    run_list: apt::default
  - name: ubuntu-14.04
    run_list: apt::default

suites:
  - name: default
    data_bags_path: "./test/fixtures/data_bags"
    run_list:
      - recipe[users_test::test_home_dir]
  - name: sysadmins
    data_bags_path: "./test/fixtures/data_bags"
    run_list:
      - recipe[users::sysadmins]