name              'users'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Creates users from a databag search'
version           '8.1.2'
source_url        'https://github.com/sous-chefs/users'
issues_url        'https://github.com/sous-chefs/users/issues'
chef_version      '>= 15.3'

supports 'aix'
supports 'amazon'
supports 'centos'
supports 'debian'
supports 'fedora'
supports 'freebsd'
supports 'mac_os_x'
supports 'opensuse'
supports 'opensuseleap'
supports 'oracle'
supports 'redhat'
supports 'scientific'
supports 'suse'
supports 'ubuntu'
supports 'zlinux'
