# frozen_string_literal: true

name              'users'
maintainer        'Sous Chefs'
maintainer_email  'help@sous-chefs.org'
license           'Apache-2.0'
description       'Provides the users_manage custom resource for managing OS users and groups'
version           '8.1.24'
source_url        'https://github.com/sous-chefs/users'
issues_url        'https://github.com/sous-chefs/users/issues'
chef_version      '>= 15.3'

supports 'aix'
supports 'almalinux', '>= 8.0'
supports 'amazon', '>= 2023.0'
supports 'centos_stream', '>= 9.0'
supports 'debian', '>= 12.0'
supports 'fedora'
supports 'freebsd', '>= 13.0'
supports 'mac_os_x'
supports 'opensuseleap', '>= 16.0'
supports 'oracle', '>= 8.0'
supports 'redhat', '>= 8.0'
supports 'rocky', '>= 8.0'
supports 'suse', '>= 15.0'
supports 'ubuntu', '>= 22.04'
supports 'zlinux'
# supports 'windows'
